### ISSUE TITLE
WLAN Channel Scan with Conbee II crashes the adapter instance

### ISSUE THREAD

**Issue by fu-zhou** [ioBroker/ioBroker.zigbee#1109]
Hi, when trying to scan the WLAN Channels with a Conbee II USB Stick, the Adapter instance crashes with the following Log-entries (first message at the bottom of the table):
zigbee.0 | 30513 | 2021-05-24 00:41:58.856 | info | Zigbee started
-- | -- | -- | -- | --
zigbee.0 | 30513 | 2021-05-24 00:41:58.855 | info | 0x5c0272fffec72814 (addr 60026): TS0201 - TuYa Temperature &amp; humidity sensor with display (EndDevice)
zigbee.0 | 30513 | 2021-05-24 00:41:58.854 | info | 0x60a423fffe536718 (addr 49154): L122CB63H11A9.0W - Aldi LIGHTWAY smart home LED-lamp - bulb (Router)
zigbee.0 | 30513 | 2021-05-24 00:41:58.852 | info | 0xbc33acfffe730e71 (addr 55095): 141L100RC - Aldi MEGOS switch and dimming light remote control (EndDevice)
zigbee.0 | 30513 | 2021-05-24 00:41:58.840 | info | Currently 3 devices are joined:
zigbee.0 | 30513 | 2021-05-24 00:41:58.838 | info | Unable to set transmit power, unsupported function.
zigbee.0 | 30513 | 2021-05-24 00:41:58.837 | info | --&gt; transmitPower : normal
zigbee.0 | 30513 | 2021-05-24 00:41:58.836 | info | Unable to disable LED, unsupported function.
zigbee.0 | 30513 | 2021-05-24 00:41:58.815 | info | Coordinator firmware version: {"type":"ConBee2/RaspBee2","meta":{"transportrev":0,"product":0,"majorrel":38,"minorrel":107,"maintrel":0,"revision":"0x266b0700"}}
zigbee.0 | 30513 | 2021-05-24 00:41:56.628 | info | Installed Version: iobroker.zigbee@1.5.5
zigbee.0 | 30513 | 2021-05-24 00:41:56.370 | info | Starting Zigbee npm ...
zigbee.0 | 30513 | 2021-05-24 00:41:56.300 | info | starting. Version 1.5.5 in /opt/iobroker/node_modules/iobroker.zigbee, node: v12.22.1, js-controller: 3.3.10
zigbee.0 | 29899 | 2021-05-24 00:41:23.759 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
zigbee.0 | 29899 | 2021-05-24 00:41:23.757 | info | terminating
zigbee.0 | 29899 | 2021-05-24 00:41:23.648 | info | Zigbee: disabling joining new devices.
zigbee.0 | 29899 | 2021-05-24 00:41:23.645 | info | cleaned everything up...
zigbee.0 | 29899 | 2021-05-24 00:41:23.628 | error | Cannot read property 'waitFor' of undefined
zigbee.0 | 29899 | 2021-05-24 00:41:23.628 | error | TypeError: Cannot read property 'waitFor' of undefined at ZigbeeController.getChannelsEnergy (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:780:54) at Commands.getChannels (/opt/iobroker/node_modules/iobroker.zigbee/lib/commands.js:421:52) at Commands.onMessage (/opt/iobroker/node_modules/iobroker.zigbee/lib/commands.js:75:30) at Zigbee.emit (events.js:326:22) at change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5629:34) at Immediate.&lt;anonymous&gt; (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:232:37) at processImmediate (internal/timers.js:461:21)
zigbee.0 | 29899 | 2021-05-24 00:41:23.626 | error | unhandled promise rejection: Cannot read property 'waitFor' of undefined

Adapter version: 1.5.5
Conbee II Firmware: latest (April 2021)

Also, if deconz/conbee is selected and output power and LED behaviour can not be set by the adapter, that option should be skipped by the adapter. Currently it is an entry in the log:
- Unable to disable LED
- Unable to set transmit power

Please let me know what I can do to help fixing the problem, I'm ready to do any kind of testing!

**Comment by asgothian** [comment]
Please start the adapter in debug mode and attempt the channel scan again, then repost the log.

A.

**Comment by fu-zhou** [comment]
I tried the COM-Port settings with:
- /dev/serial/by-id/usb-dresden_elektronik_ingenieurtechnik_GmbH_ConBee_II_...
- /dev/ttyACM0
The adapter works with both settings while the WLAN scan does not work in both cases.

I set the Log-Level of the instance to "debug" - hope this is what you meant. After doing the WLAN scan the log file entries look like:


host.iobroker-vm | 2021-05-25 11:37:16.544 | info | instance system.adapter.zigbee.0 started with pid 98366
-- | -- | -- | --
host.iobroker-vm | 2021-05-25 11:36:46.512 | info | Restart adapter system.adapter.zigbee.0 because enabled
host.iobroker-vm | 2021-05-25 11:36:46.509 | error | instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
zigbee.0 | 2021-05-25 11:36:45.946 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
zigbee.0 | 2021-05-25 11:36:45.945 | info | terminating
zigbee.0 | 2021-05-25 11:36:45.468 | debug | Publish LQ for 0x7cb03eaa0a0304b5 = 0
zigbee.0 | 2021-05-25 11:36:45.467 | debug | Publish available for 0x7cb03eaa0a0304b5 = false
zigbee.0 | 2021-05-25 11:36:45.465 | debug | Publish LQ for 0x84182600000aebbb = 0
zigbee.0 | 2021-05-25 11:36:45.464 | debug | Publish available for 0x84182600000aebbb = false
zigbee.0 | 2021-05-25 11:36:45.462 | debug | Publish LQ for 0x5c0272fffec72814 = 0
zigbee.0 | 2021-05-25 11:36:45.460 | debug | Publish available for 0x5c0272fffec72814 = false
zigbee.0 | 2021-05-25 11:36:45.459 | debug | Publish LQ for 0xbc33acfffe730e71 = 0
zigbee.0 | 2021-05-25 11:36:45.457 | debug | Publish available for 0xbc33acfffe730e71 = false
zigbee.0 | 2021-05-25 11:36:45.446 | info | Zigbee: disabling joining new devices.
zigbee.0 | 2021-05-25 11:36:45.443 | info | cleaned everything up...
zigbee.0 | 2021-05-25 11:36:45.440 | error | Cannot read property 'waitFor' of undefined
zigbee.0 | 2021-05-25 11:36:45.440 | error | TypeError: Cannot read property 'waitFor' of undefined at ZigbeeController.getChannelsEnergy (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:780:54) at Commands.getChannels (/opt/iobroker/node_modules/iobroker.zigbee/lib/commands.js:421:52) at Commands.onMessage (/opt/iobroker/node_modules/iobroker.zigbee/lib/commands.js:75:30) at Zigbee.emit (events.js:326:22) at change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5634:34) at Immediate.&lt;anonymous&gt; (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:232:37) at processImmediate (internal/timers.js:461:21)
zigbee.0 | 2021-05-25 11:36:45.438 | error | unhandled promise rejection: Cannot read property 'waitFor' of undefined
zigbee.0 | 2021-05-25 11:36:45.437 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 2021-05-25 11:36:42.246 | debug | Routing table succeeded for 'Coordinator'
zigbee.0 | 2021-05-25 11:36:42.245 | debug | Routing for 'Coordinator': {"table":[{"destinationAddress":20831,"status":"ACTIVE","nextHop":20831},{"destinationAddress":8179,"status":"ACTIVE","nextHop":8179}]}
zigbee.0 | 2021-05-25 11:36:42.228 | debug | LQI succeeded for 'Coordinator'
zigbee.0 | 2021-05-25 11:36:41.810 | debug | sendTo "listUart" to system.adapter.admin.0 from system.adapter.zigbee.0
zigbee.0 | 2021-05-25 11:36:41.810 | debug | List of ports: [{"comName":"/dev/ttyACM0"},{"comName":"/dev/ttyS1"},{"comName":"/dev/ttyS10"},{"comName":"/dev/ttyS11"},{"comName":"/dev/ttyS12"},{"comName":"/dev/ttyS13"},{"comName":"/dev/ttyS14"},{"comName":"/dev/ttyS15"},{"comName":"/dev/ttyS16"},{"comName":"/dev/ttyS17"},{"comName":"/dev/ttyS18"},{"comName":"/dev/ttyS19"},{"comName":"/dev/ttyS2"},{"comName":"/dev/ttyS20"},{"comName":"/dev/ttyS21"},{"comName":"/dev/ttyS22"},{"comName":"/dev/ttyS23"},{"comName":"/dev/ttyS24"},{"comName":"/dev/ttyS25"},{"comName":"/dev/ttyS26"},{"comName":"/dev/ttyS27"},{"comName":"/dev/ttyS28"},{"comName":"/dev/ttyS29"},{"comName":"/dev/ttyS3"},{"comName":"/dev/ttyS30"},{"comName":"/dev/ttyS31"},{"comName":"/dev/ttyS4"},{"comName":"/dev/ttyS5"},{"comName":"/dev/ttyS6"},{"comName":"/dev/ttyS7"},{"comName":"/dev/ttyS8"},{"comName":"/dev/ttyS9"},{"comName":"/dev/ttyS0"}]
zigbee.0 | 2021-05-25 11:36:41.724 | debug | sendTo "getExclude" to system.adapter.admin.0 from system.adapter.zigbee.0
zigbee.0 | 2021-05-25 11:36:41.715 | debug | getExclude result: []
zigbee.0 | 2021-05-25 11:36:41.712 | debug | sendTo "getBinding" to system.adapter.admin.0 from system.adapter.zigbee.0
zigbee.0 | 2021-05-25 11:36:41.712 | debug | getBinding result: []
zigbee.0 | 2021-05-25 11:36:41.614 | debug | sendTo "getDevices" to system.adapter.admin.0 from system.adapter.zigbee.0

**Comment by asgothian** [comment]
Thanks for the test. I can now verify which part of the code will crash the adapter and introduce a fix

**Comment by fu-zhou** [comment]
Thanks, awesome news!!!

**Comment by fu-zhou** [comment]
@asgothian I installed 1.5.6 - same behaviour still (I know you didn't claim that it is fixed in that version). The log shows messages I never had before:



zigbee.0 | 2021-05-29 20:35:25.584 | warn | State value to set for "zigbee.0.84fd27fffe5f07df.link_quality" has value "255" greater than max "254"
-- | -- | -- | --
zigbee.0 | 2021-05-29 20:35:25.426 | warn | State value to set for "zigbee.0.7cb03eaa0a0304b5.link_quality" has value "255" greater than max "254"
zigbee.0 | 2021-05-29 20:35:24.996 | warn | State value to set for "zigbee.0.60a423fffe536718.link_quality" has value "255" greater than max "254"



The referenced devices are fairly close to the Zigbee Coordinator and the map indeed shows "255"...

**Comment by asgothian** [comment]
Please install my test branch from
https://github.com/asgothian/ioBroker.zigbee/tarball/zigbee_1_5_6. It should fix the crash issue.

A.

**Comment by fu-zhou** [comment]
I just installed from Github. The installer warned about the wrong OS ("Darwin" expectec, "Linux" found) but the adpater got installed eventually. Unfortunately the WLAN scan still crashes the instance. Here is the debug log:

host.iobroker-vm | &nbsp; | 2021-05-30 22:53:57.285 | info | Restart adapter system.adapter.zigbee.0 because enabled
-- | -- | -- | -- | --
host.iobroker-vm | &nbsp; | 2021-05-30 22:53:57.284 | error | instance system.adapter.zigbee.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
zigbee.0 | 19840 | 2021-05-30 22:53:56.702 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
zigbee.0 | 19840 | 2021-05-30 22:53:56.701 | info | terminating
zigbee.0 | 19840 | 2021-05-30 22:53:56.241 | debug | Publish LQ for 0x84fd27fffe5f07df = 0
zigbee.0 | 19840 | 2021-05-30 22:53:56.241 | debug | Publish available for 0x84fd27fffe5f07df = false
zigbee.0 | 19840 | 2021-05-30 22:53:56.240 | debug | Publish LQ for 0x7cb03eaa0a0304b5 = 0
zigbee.0 | 19840 | 2021-05-30 22:53:56.240 | debug | Publish available for 0x7cb03eaa0a0304b5 = false
zigbee.0 | 19840 | 2021-05-30 22:53:56.239 | debug | Publish LQ for 0x84182600000aebbb = 0
zigbee.0 | 19840 | 2021-05-30 22:53:56.238 | debug | Publish available for 0x84182600000aebbb = false
zigbee.0 | 19840 | 2021-05-30 22:53:56.237 | debug | Publish LQ for 0x5c0272fffec72814 = 0
zigbee.0 | 19840 | 2021-05-30 22:53:56.236 | debug | Publish available for 0x5c0272fffec72814 = false
zigbee.0 | 19840 | 2021-05-30 22:53:56.235 | debug | Publish LQ for 0x60a423fffe536718 = 0
zigbee.0 | 19840 | 2021-05-30 22:53:56.234 | debug | Publish available for 0x60a423fffe536718 = false
zigbee.0 | 19840 | 2021-05-30 22:53:56.230 | debug | Publish LQ for 0xbc33acfffe730e71 = 0
zigbee.0 | 19840 | 2021-05-30 22:53:56.227 | debug | Publish available for 0xbc33acfffe730e71 = false
zigbee.0 | 19840 | 2021-05-30 22:53:56.204 | info | Zigbee: disabling joining new devices.
zigbee.0 | 19840 | 2021-05-30 22:53:56.201 | info | cleaned everything up...
zigbee.0 | 19840 | 2021-05-30 22:53:56.198 | error | Cannot read property 'waitFor' of undefined
zigbee.0 | 19840 | 2021-05-30 22:53:56.197 | error | TypeError: Cannot read property 'waitFor' of undefined at ZigbeeController.getChannelsEnergy (/opt/iobroker/node_modules/iobroker.zigbee/lib/zigbeecontroller.js:806:54) at Commands.getChannels (/opt/iobroker/node_modules/iobroker.zigbee/lib/commands.js:421:52) at Commands.onMessage (/opt/iobroker/node_modules/iobroker.zigbee/lib/commands.js:75:30) at Zigbee.emit (events.js:326:22) at change (/opt/iobroker/node_modules/iobroker.js-controller/lib/adapter.js:5634:34) at Immediate.&lt;anonymous&gt; (/opt/iobroker/node_modules/@iobroker/db-states-redis/lib/states/statesInRedisClient.js:232:37) at processImmediate (internal/timers.js:461:21)
zigbee.0 | 19840 | 2021-05-30 22:53:56.196 | error | unhandled promise rejection: Cannot read property 'waitFor' of undefined
zigbee.0 | 19840 | 2021-05-30 22:53:56.195 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
zigbee.0 | 19840 | 2021-05-30 22:53:45.482 | debug | sendTo "getExclude" to system.adapter.admin.0 from system.adapter.zigbee.0
zigbee.0 | 19840 | 2021-05-30 22:53:45.433 | debug | getExclude result: []
zigbee.0 | 19840 | 2021-05-30 22:53:45.432 | debug | sendTo "getBinding" to system.adapter.admin.0 from system.adapter.zigbee.0
zigbee.0 | 19840 | 2021-05-30 22:53:45.431 | debug | getBinding result: []
zigbee.0 | 19840 | 2021-05-30 22:53:45.292 | debug | sendTo "getMap" to system.adapter.admin.0 from system.adapter.zigbee.0
zigbee.0 | 19840 | 2021-05-30 22:53:45.291 | debug | getMap result: {"lqis":[{"parent":"0x00212effff05b79c","networkAddress":8179,"ieeeAddr":"0x7cb03eaa0a0304b5","lqi":255,"relationship":2,"depth":1,"status":"online"},{"parent":"0x00212effff05b79c","networkAddress":63598,"ieeeAddr":"0x60a423fffe536718","lqi":252,"relationship":2,"depth":1,"status":"online"},{"parent":"0x00212effff05b79c","networkAddress":25879,"ieeeAddr":"0x84fd27fffe5f07df","lqi":255,"relationship":2,"depth":1,"status":"online"},{"parent":"0x00212effff05b79c","networkAddress":20831,"ieeeAddr":"0x84182600000aebbb","lqi":212,"relationship":2,"depth":1,"status":"online"},{"parent":"0x60a423fffe536718","networkAddress":0,"ieeeAddr":"0x00212effff05b79c","lqi":213,"relationship":2,"depth":0,"status":"online"},{"parent":"0x60a423fffe536718","networkAddress":8179,"ieeeAddr":"0x7cb03eaa0a0304b5","lqi":39,"relationship":2,"depth":15,"status":"online"},{"parent":"0x60a423fffe536718","networkAddress":25879,"ieeeAddr":"0x84fd27fffe5f07df","lqi":148,"relationship":2,"depth":15,"status":"online"},{"parent":"0x84182600000aebbb","networkAddress":0,"ieeeAddr":"0x00212effff05b79c","lqi":62,"relationship":2,"depth":1,"status":"online"},{"parent":"0x84182600000aebbb","networkAddress":60026,"ieeeAddr":"0x5c0272fffec72814","lqi":50,"relationship":1,"depth":1,"status":"online"},{"parent":"0x84182600000aebbb","networkAddress":25879,"ieeeAddr":"0x84fd27fffe5f07df","lqi":22,"relationship":2,"depth":1,"status":"online"},{"parent":"0x84182600000aebbb","networkAddress":55095,"ieeeAddr":"0xbc33acfffe730e71","lqi":80,"relationship":1,"depth":1,"status":"online"},{"parent":"0x7cb03eaa0a0304b5","networkAddress":0,"ieeeAddr":"0x00212effff05b79c","lqi":88,"relationship":2,"depth":1,"status":"online"},{"parent":"0x7cb03eaa0a0304b5","networkAddress":63598,"ieeeAddr":"0x60a423fffe536718","lqi":8,"relationship":2,"depth":1,"status":"online"},{"parent":"0x7cb03eaa0a0304b5","networkAddress":25879,"ieeeAddr":"0x84fd27fffe5f07df","lqi":48,"relationship":2,"depth":1,"status":"online"},{"parent":"0x84fd27fffe5f07df","networkAddress":0,"ieeeAddr":"0x00212effff05b79c","lqi":195,"relationship":2,"depth":0,"status":"online"},{"parent":"0x84fd27fffe5f07df","networkAddress":8179,"ieeeAddr":"0x7cb03eaa0a0304b5","lqi":119,"relationship":2,"depth":15,"status":"online"},{"parent":"0x84fd27fffe5f07df","networkAddress":20831,"ieeeAddr":"0x84182600000aebbb","lqi":57,"relationship":2,"depth":15,"status":"online"},{"parent":"0x84fd27fffe5f07df","networkAddress":63598,"ieeeAddr":"0x60a423fffe536718","lqi":141,"relationship":2,"depth":15,"status":"online"}],"routing":[{"source":"0x00212effff05b79c","destination":25879,"nextHop":25879,"status":"ACTIVE"},{"source":"0x00212effff05b79c","destination":63598,"nextHop":63598,"status":"ACTIVE"},{"source":"0x00212effff05b79c","destination":20831,"nextHop":20831,"status":"ACTIVE"},{"source":"0x00212effff05b79c","destination":8179,"nextHop":8179,"status":"ACTIVE"},{"source":"0x00212effff05b79c","destination":55095,"nextHop":20831,"status":"ACTIVE"},{"source":"0x00212effff05b79c","destination":60026,"nextHop":20831,"status":"ACTIVE"},{"source":"0x60a423fffe536718","destination":0,"nextHop":0,"status":"ACTIVE"},{"source":"0x60a423fffe536718","destination":0,"nextHop":0,"status":"ACTIVE"},{"source":"0x60a423fffe536718","destination":0,"nextHop":0,"status":"ACTIVE"},{"source":"0x60a423fffe536718","destination":0,"nextHop":0,"status":"ACTIVE"},{"source":"0x60a423fffe536718","destination":0,"nextHop":0,"status":"ACTIVE"},{"source":"0x60a423fffe536718","destination":0,"nextHop":0,"status":"ACTIVE"},{"source":"0x60a423fffe536718","destination":0,"nextHop":0,"status":"ACTIVE"},{"source":"0x60a423fffe536718","destination":0,"nextHop":0,"status":"ACTIVE"},{"source":"0x60a423fffe536718","destination":0,"nextHop":0,"status":"ACTIVE"},{"source":"0x60a423fffe536718","destination":0,"nextHop":0,"status":"ACTIVE"},{"source":"0x84fd27fffe5f07df","destination":0,"nextHop":0,"status":"ACTIVE"},{"source":"0x84fd27fffe5f07df","destination":0,"nextHop":0,"status":"ACTIVE"},{"source":"0x84fd27fffe5f07df","destination":0,"nextHop":0,"status":"ACTIVE"},{"source":"0x84fd27fffe5f07df","destination":0,"nextHop":0,"status":"ACTIVE"},{"source":"0x84fd27fffe5f07df","destination":0,"nextHop":0,"status":"ACTIVE"},{"source":"0x84fd27fffe5f07df","destination":0,"nextHop":0,"status":"ACTIVE"},{"source":"0x84fd27fffe5f07df","destination":0,"nextHop":0,"status":"ACTIVE"},{"source":"0x84fd27fffe5f07df","destination":0,"nextHop":0,"status":"ACTIVE"},{"source":"0x84fd27fffe5f07df","destination":0,"nextHop":0,"status":"ACTIVE"},{"source":"0x84fd27fffe5f07df","destination":0,"nextHop":0,"status":"ACTIVE"}]}
zigbee.0 | 19840 | 2021-05-30 22:53:45.291 | debug | Get map succeeded [{"parent":"0x00212effff05b79c","networkAddress":8179,"ieeeAddr":"0x7cb03eaa0a0304b5","lqi":255,"relationship":2,"depth":1,"status":"online"},{"parent":"0x00212effff05b79c","networkAddress":63598,"ieeeAddr":"0x60a423fffe536718","lqi":252,"relationship":2,"depth":1,"status":"online"},{"parent":"0x00212effff05b79c","networkAddress":25879,"ieeeAddr":"0x84fd27fffe5f07df","lqi":255,"relationship":2,"depth":1,"status":"online"},{"parent":"0x00212effff05b79c","networkAddress":20831,"ieeeAddr":"0x84182600000aebbb","lqi":212,"relationship":2,"depth":1,"status":"online"},{"parent":"0x60a423fffe536718","networkAddress":0,"ieeeAddr":"0x00212effff05b79c","lqi":213,"relationship":2,"depth":0,"status":"online"},{"parent":"0x60a423fffe536718","networkAddress":8179,"ieeeAddr":"0x7cb03eaa0a0304b5","lqi":39,"relationship":2,"depth":15,"status":"online"},{"parent":"0x60a423fffe536718","networkAddress":25879,"ieeeAddr":"0x84fd27fffe5f07df","lqi":148,"relationship":2,"depth":15,"status":"online"},{"parent":"0x84182600000aebbb","networkAddress":0,"ieeeAddr":"0x00212effff05b79c","lqi":62,"relationship":2,"depth":1,"status":"online"},{"parent":"0x84182600000aebbb","networkAddress":60026,"ieeeAddr":"0x5c0272fffec72814","lqi":50,"relationship":1,"depth":1,"status":"online"},{"parent":"0x84182600000aebbb","networkAddress":25879,"ieeeAddr":"0x84fd27fffe5f07df","lqi":22,"relationship":2,"depth":1,"status":"online"},{"parent":"0x84182600000aebbb","networkAddress":55095,"ieeeAddr":"0xbc33acfffe730e71","lqi":80,"relationship":1,"depth":1,"status":"online"},{"parent":"0x7cb03eaa0a0304b5","networkAddress":0,"ieeeAddr":"0x00212effff05b79c","lqi":88,"relationship":2,"depth":1,"status":"online"},{"parent":"0x7cb03eaa0a0304b5","networkAddress":63598,"ieeeAddr":"0x60a423fffe536718","lqi":8,"relationship":2,"depth":1,"status":"online"},{"parent":"0x7cb03eaa0a0304b5","networkAddress":25879,"ieeeAddr":"0x84fd27fffe5f07df","lqi":48,"relationship":2,"depth":1,"status":"online"},{"parent":"0x84fd27fffe5f07df","networkAddress":0,"ieeeAddr":"0x00212effff05b79c","lqi":195,"relationship":2,"depth":0,"status":"online"},{"parent":"0x84fd27fffe5f07df","networkAddress":8179,"ieeeAddr":"0x7cb03eaa0a0304b5","lqi":119,"relationship":2,"depth":15,"status":"online"},{"parent":"0x84fd27fffe5f07df","networkAddress":20831,"ieeeAddr":"0x84182600000aebbb","lqi":57,"relationship":2,"depth":15,"status":"online"},{"parent":"0x84fd27fffe5f07df","networkAddress":63598,"ieeeAddr":"0x60a423fffe536718","lqi":141,"relationship":2,"depth":15,"status":"online"}]
zigbee.0 | 19840 | 2021-05-30 22:53:45.290 | debug | Routing table succeeded for '0x84fd27fffe5f07df'
zigbee.0 | 19840 | 2021-05-30 22:53:45.290 | debug | Routing for '0x84fd27fffe5f07df': {"table":[{"destinationAddress":0,"status":"ACTIVE","nextHop":0},{"destinationAddress":0,"status":"ACTIVE","nextHop":0},{"destinationAddress":0,"status":"ACTIVE","nextHop":0},{"destinationAddress":0,"status":"ACTIVE","nextHop":0},{"destinationAddress":0,"status":"ACTIVE","nextHop":0},{"destinationAddress":0,"status":"ACTIVE","nextHop":0},{"destinationAddress":0,"status":"ACTIVE","nextHop":0},{"destinationAddress":0,"status":"ACTIVE","nextHop":0},{"destinationAddress":0,"status":"ACTIVE","nextHop":0},{"destinationAddress":0,"status":"ACTIVE","nextHop":0}]}
zigbee.0 | 19840 | 2021-05-30 22:53:45.263 | debug | LQI succeeded for '0x84fd27fffe5f07df'
zigbee.0 | 19840 | 2021-05-30 22:53:45.204 | debug | Routing table succeeded for '0x7cb03eaa0a0304b5'
zigbee.0 | 19840 | 2021-05-30 22:53:45.204 | debug | Routing for '0x7cb03eaa0a0304b5': {"neighbors":[{"linkquality":88,"networkAddress":0,"ieeeAddr":"0x00212effff05b79c","relationship":2,"depth":1},{"linkquality":8,"networkAddress":63598,"ieeeAddr":"0x60a423fffe536718","relationship":2,"depth":1},{"linkquality":48,"networkAddress":25879,"ieeeAddr":"0x84fd27fffe5f07df","relationship":2,"depth":1}]}
zigbee.0 | 19840 | 2021-05-30 22:53:45.141 | debug | LQI succeeded for '0x7cb03eaa0a0304b5'
zigbee.0 | 19840 | 2021-05-30 22:53:45.088 | debug | Routing table succeeded for '0x84182600000aebbb'
zigbee.0 | 19840 | 2021-05-30 22:53:45.087 | debug | Routing for '0x84182600000aebbb': {"neighbors":[{"linkquality":62,"networkAddress":0,"ieeeAddr":"0x00212effff05b79c","relationship":2,"depth":1},{"linkquality":50,"networkAddress":60026,"ieeeAddr":"0x5c0272fffec72814","relationship":1,"depth":1},{"linkquality":22,"networkAddress":25879,"ieeeAddr":"0x84fd27fffe5f07df","relationship":2,"depth":1},{"linkquality":80,"networkAddress":55095,"ieeeAddr":"0xbc33acfffe730e71","relationship":1,"depth":1}]}
zigbee.0 | 19840 | 2021-05-30 22:53:45.042 | debug | LQI succeeded for '0x84182600000aebbb'
zigbee.0 | 19840 | 2021-05-30 22:53:44.948 | debug | Routing table succeeded for '0x60a423fffe536718'
zigbee.0 | 19840 | 2021-05-30 22:53:44.947 | debug | Routing for '0x60a423fffe536718': {"table":[{"destinationAddress":0,"status":"ACTIVE","nextHop":0},{"destinationAddress":0,"status":"ACTIVE","nextHop":0},{"destinationAddress":0,"status":"ACTIVE","nextHop":0},{"destinationAddress":0,"status":"ACTIVE","nextHop":0},{"destinationAddress":0,"status":"ACTIVE","nextHop":0},{"destinationAddress":0,"status":"ACTIVE","nextHop":0},{"destinationAddress":0,"status":"ACTIVE","nextHop":0},{"destinationAddress":0,"status":"ACTIVE","nextHop":0},{"destinationAddress":0,"status":"ACTIVE","nextHop":0},{"destinationAddress":0,"status":"ACTIVE","nextHop":0}]}
zigbee.0 | 19840 | 2021-05-30 22:53:44.908 | debug | LQI succeeded for '0x60a423fffe536718'
zigbee.0 | 19840 | 2021-05-30 22:53:44.873 | debug | Routing table succeeded for 'Coordinator'
zigbee.0 | 19840 | 2021-05-30 22:53:44.872 | debug | Routing for 'Coordinator': {"table":[{"destinationAddress":25879,"status":"ACTIVE","nextHop":25879},{"destinationAddress":63598,"status":"ACTIVE","nextHop":63598},{"destinationAddress":20831,"status":"ACTIVE","nextHop":20831},{"destinationAddress":8179,"status":"ACTIVE","nextHop":8179},{"destinationAddress":55095,"status":"ACTIVE","nextHop":20831},{"destinationAddress":60026,"status":"ACTIVE","nextHop":20831}]}
zigbee.0 | 19840 | 2021-05-30 22:53:44.826 | debug | LQI succeeded for 'Coordinator'
zigbee.0 | 19840 | 2021-05-30 22:53:44.463 | debug | sendTo "listUart" to system.adapter.admin.0 from system.adapter.zigbee.0
zigbee.0 | 19840 | 2021-05-30 22:53:44.463 | debug | List of ports: [{"comName":"/dev/ttyACM0"},{"comName":"/dev/ttyS1"},{"comName":"/dev/ttyS10"},{"comName":"/dev/ttyS11"},{"comName":"/dev/ttyS12"},{"comName":"/dev/ttyS13"},{"comName":"/dev/ttyS14"},{"comName":"/dev/ttyS15"},{"comName":"/dev/ttyS16"},{"comName":"/dev/ttyS17"},{"comName":"/dev/ttyS18"},{"comName":"/dev/ttyS19"},{"comName":"/dev/ttyS2"},{"comName":"/dev/ttyS20"},{"comName":"/dev/ttyS21"},{"comName":"/dev/ttyS22"},{"comName":"/dev/ttyS23"},{"comName":"/dev/ttyS24"},{"comName":"/dev/ttyS25"},{"comName":"/dev/ttyS26"},{"comName":"/dev/ttyS27"},{"comName":"/dev/ttyS28"},{"comName":"/dev/ttyS29"},{"comName":"/dev/ttyS3"},{"comName":"/dev/ttyS30"},{"comName":"/dev/ttyS31"},{"comName":"/dev/ttyS4"},{"comName":"/dev/ttyS5"},{"comName":"/dev/ttyS6"},{"comName":"/dev/ttyS7"},{"comName":"/dev/ttyS8"},{"comName":"/dev/ttyS9"},{"comName":"/dev/ttyS0"}]
zigbee.0 | 19840 | 2021-05-30 22:53:44.246 | debug | sendTo "getDevices" to system.adapter.admin.0 from system.adapter.zigbee.0

**Comment by asgothian** [comment]
I apologize - seems i forgot to push the changes to GitHub.

Can you please install again from the  link above ?

**Comment by fu-zhou** [comment]
WLAN scans don't crash the instance any more - following error message shows immediately after trying to start the scan:
```
Error
The coordinator does not support channel scans
```
Is that okay, does the ConBee II stick really not support channel scans or is it just not implemented yet?

**Comment by asgothian** [comment]
I admit that i do not know the full answer to that.

Fact is that the function which is called to scan the network is not present in the code for conbee/raspbee, which is why i set the adapter to generate the message rather than crash.

A.

**Comment by fu-zhou** [comment]
If WLAN scan works with Conbee2 that would be the frosting...
