### ISSUE TITLE
Huarui Lighting Co. - Triac Dimmable LED Driver - for LED panels - e.g 20, 30, 40Watt

### ISSUE THREAD

**Issue by StifflersMom007** [ioBroker/ioBroker.zigbee#125]
Hello dear community,
I found a great LED driver for panels with higher voltage (32V - 45V) for 20€

**The brand:** china... Huarui Lightning
https://www.ebay.de/itm/230V-8W-40W-ZIGBEE-3-0-Led-Dimmbar-Konstantstromquelle-Treiber-APP-for-Echo-Plus/123496064002?hash=item1cc0f06402:m:mlGgNcd9_ZWqZyuy4PIdxhA:rk:1:pf:0

**The issue:** 
I can find it over iobroker, but there are no functions or entries possible in the object section. 

![zigbee - led driver](https://user-images.githubusercontent.com/45979585/50180567-4729f880-030a-11e9-9f24-7aa881750cbc.png)
![zigbee - led driver -2](https://user-images.githubusercontent.com/45979585/50180569-485b2580-030a-11e9-94f3-ee1bc8dfe97b.png)

the question: does sombody see a solution, I think enable LED panels into the zigbee network with a dimming optioin is a great idea.

**Comment by arteck** [comment]
check my repo https://github.com/arteck/ioBroker.zigbee

**Comment by StifflersMom007** [comment]
Hi Arteck, you are the best! Works great with the new version!
Thank you very much!! and happy new year!

**Comment by arteck** [comment]
done

**Comment by StifflersMom007** [comment]
still get the 0.8.2a version installed and still not working.

Do I have to install another version?

Regards
