### ISSUE TITLE
GLEDOPTO LED bulb

### ISSUE THREAD

**Issue by obodeldog** [ioBroker/ioBroker.zigbee#136]
Hi!
I tested this one: https://www.aliexpress.com/item/GLEDOPTO-LED-ZIGBEE-12W-RGB-CCT-bulb-AC100-240V-RGB-and-dual-white-e27-e26-dimmer/32906939699.html?spm=a2g0s.9042311.0.0.40d14c4dSq2UmY

The device was found:

<img width="506" alt="50521148-90293c00-0ac4-11e9-8eaa-fd261d6fc496" src="https://user-images.githubusercontent.com/35403739/50575883-92620200-0e06-11e9-8163-aa0ebf8e5fa3.png">

But there are no devices in "Objekte" -> "zigbee".
Since this is my first Zigbee device, I would like to know if the objects should normally appear here?

**Comment by arteck** [comment]
done

**Comment by modmax** [comment]
This issue can be closed then.

**Comment by obodeldog** [comment]
Hi! Still not found correctly
![image](https://user-images.githubusercontent.com/35403739/51929574-d8f04f80-23f8-11e9-81a1-87b84181584e.png)
