### ISSUE TITLE
JS Bug in TS000F

### ISSUE THREAD

**Issue by schwaigi** [ioBroker/ioBroker.zigbee#1620]
Hello

log filled with this lines:

DeviceConfigure:Failed to DeviceConfigure.configure 0xa4c1386a9f2f6bc6 TS000F (TypeError: Cannot read property 'debug' of undefined at Object.configureMagicPacket (C:\iobroker\SmartHome\node_modules\zigbee-herdsman-converters\lib\tuya.js:1183:20) at Object.configure (C:\iobroker\SmartHome\node_modules\zigbee-herdsman-converters\devices\tuya.js:1835:13) at DeviceConfigure.doConfigure (C:\iobroker\SmartHome\node_modules\iobroker.zigbee\lib\zbDeviceConfigure.js:134:13) at DeviceConfigure.configure (C:\iobroker\SmartHome\node_modules\iobroker.zigbee\lib\zbDeviceConfigure.js:112:17))

Greets
Toni

**Comment by asgothian** [comment]
- Which adapter version

- The issue is raised in a library (zigbee-herdsman-converters) and should be fixed there.

**Comment by schwaigi** [comment]
1.8.10

**Comment by Canadamusikus** [comment]
Hi, I have the same problem. At first, the file tuya.js was not there, then I added it, I let the iob fix run then. Still the same problem.

**Comment by Canadamusikus** [comment]
The solution is from another chat in github :UseeLink SM-0306E-2W: Failed to DeviceConfigure.configure #1629 
attempt to patch /opt/iobroker/node_modules/iobroker.zigbee/lib/zbDeviceConfigure.js, line 134

from

           await mappedDevice.configure(device, coordinatorEndpoint);
to

         await mappedDevice.configure(device, coordinatorEndpoint, this);

I think this solves it without the need to add tuya.js (I renamed the file and reconfiguring still worked.)
