### ISSUE TITLE
DeviceConfigure:Failed TuYa 10A UK or 16A EU smart plug

### ISSUE THREAD

**Issue by RcTomcat1** [ioBroker/ioBroker.zigbee#1650]
Hi,

I just tried to get my CC2652RB Stick up and running but I can't get it to configure my device.
```
<html><body>
<!--StartFragment-->

  | DeviceConfigure:Failed  to DeviceConfigure.configure 0x60a423fffe5e3274 TS0121 (Error: Bind  0x60a423fffe5e3274/1 genOnOff from '0x00124b001936a498/1' failed (AREQ -  ZDO - bindRsp after 10000ms)     at Timeout._onTimeout  (/opt/iobroker/node_modules/zigbee-herdsman/src/utils/waitress.ts:64:35)     at listOnTimeout (node:internal/timers:564:17)     at processTimers (node:internal/timers:507:7))
-- | --


<!--EndFragment-->
</body>
</html>
```
Pairing is successful according to the iobroker log.
I can't make sense of what the issue might be besides a timeout, hence this post.

**Comment by asgothian** [comment]
The plug does not respond to the bind request. There are 4 possible reasons for this:
- No connection: The plug cannot receive the device configure request
- No connection 2: The plug accepts the request but the response does not reach the coordinator
- Wrong Converter: It is a Tuya Device. It is not uncommon for such devices to not behave consistent with other devices which look / identify in the same way
- Firmware error on the device.


A.

**Comment by RcTomcat1** [comment]
I already had the device up and running for well over a year now. Decided to go with the new ZigBee stick due to some range issues. With my old ZigBee stick I could easily turn the device on and off so it must have something to do with the new ZigBee stick. It is the one from slae listed on the compatibility list.
I will try to revert to the old stick and see if the problem persists.

On Jan 10, 2023 19:07, asgothian ***@***.***> wrote:

The plug does not respond to the bind request. There are 4 possible reasons for this:

  *   No connection: The plug cannot receive the device configure request
  *   No connection 2: The plug accepts the request but the response does not reach the coordinator
  *   Wrong Converter: It is a Tuya Device. It is not uncommon for such devices to not behave consistent with other devices which look / identify in the same way
  *   Firmware error on the device.

A.

**Comment by asgothian** [comment]
Keep in mind that 2.4 Wireless signals are prone to be affected by reflections, antenna location, antenna orientation and other issues.

**Comment by RcTomcat1** [comment]
I know but the device is half a meter away from the stick ;)
That should be a distance that is manageable ^^

**Comment by RcTomcat1** [comment]
I will check if the error persists with the old ZigBee stick. That might narrow it down to the new stick or not.

**Comment by RcTomcat1** [comment]
So reverting to the CC2531 gives back this:
DeviceConfigure successful 0x60a423fffe5e3274 TS0121
Works like a charm
Going with the CC2652RB states that the device cannot be configured.

**Comment by asgothian** [comment]
Read above. Especially the moment about reflections and antenna directions.
Try moving the new stick away from the system with an extension cord and change its orientation

**Comment by RcTomcat1** [comment]
The new stick is connected via a 20cm USB cable. I know how an antenna broadcasts the signal. That should not be the problem here.
Even if the plug sits 3,85cm next to the antenna of the CC2652RB it still gives the configuration error while the plug 3 meters away (Monitor and a bookcase in the way) works with the CC2531 without issues. 

If I use the CC2531 everything works, if I try with the CC2652RB -> configuration error regardless of proximity or antenna orientation.

**Comment by RcTomcat1** [comment]
Update:
I tested another Tuya Plug: TS011F_plug_1
Same issue,

**Comment by asgothian** [comment]
Please update to the latest GitHub adapter version. There was an issue in an underlying library - it should be fixed now

**Comment by RcTomcat1** [comment]
I am running 1.8.10 and just tried updating from github.
Issue persists.

**Comment by RcTomcat1** [comment]
Issue affects an TS011F_plug_1  too
