### ISSUE TITLE
GIEX GX03

### ISSUE THREAD

**Issue by Shakira10** [ioBroker/ioBroker.zigbee#2481]
### describe the problem in Detail. What do you expect to happen ? What does happen ?

Hello everyone,

I am the owner of a GX03 – 2 zone watering timer.

Issue Description:

When I turn on valve 2, valve 1 also turns on shortly afterward, even though I haven't activated it.
Once the set time for valve 2 ends, valve 2 turns off correctly, but valve 1 remains on and doesn't turn off automatically.
The time in Valve 1 does not count down correctly, even when only Valve 1 is activated.

This issue was resolved in Zigbee2MQTT with the recent update 2.3.0 (see #9266 GIEX GX03: fix valve_2 status – @Giexperience).
However, the problem still persists when using the Zigbee adapter version 3.0.1.

Another issue I noticed is that in the object tree, you can change the minutes under Countdown, but after a short time, they revert back to 1440.

Here is my hardware setup:

Raspberry Pi
OS: Linux
Architecture: ARM64
CPUs: 4 (Cortex-A72 @ 1800 MHz)
RAM: 7.6 GB
Node.js: v20.19.1
NPM: 10.8.2
Total adapters: 568
Disk size: 117.0 GB
Free disk space: 102.6 GB

Zigbee Coordinator Info:
Type: zStack3x0
Version: 2-1.2.7.1
Revision: 20230507
Port: /dev/serial/by-id/usb-ITead_Sonoff_Zigbee_3.0_USB_Dongle_Plus

Device Info:
Model: GX03
Description: GIEX 2 zone watering timer
Zigbee Model: TS0601
Type: EndDevice
Manufacturer: _TZE284_8zizsafo
Power: Battery
App Version: 68
Hardware Version: 1
ZCL Version: 3
Stack Version: 0
Interviewed: true
Configured: true
Endpoint: 1
Profile: 260
Input Clusters:
genBasic (0)
genGroups (4)
genScenes (5)
manuSpecificTuya (61184)
genBasic (0)
zosungIRTransmit (60672)
Output Clusters:
genOta (25)
genTime (10)

Thanks in advance!

### Adapter version

3.0.1

### Coordinator firmware version

2-1.2.7.1

### Coordinator

Type: zStack3x0

### Setup

Raspberry Pi

**Comment by asgothian** [comment]
This is an issue which needs to fixed in the zigbee-herdsman-converters. Please verify at the respective repository (koenkk/zigbee-herdsman-converters) for an issue / fix, noting the version of ZHC this has been fixed in.

Fixes in the ZHC will in time appear in the iobroker.zigbee adapter as well.

**Comment by TbsJah** [comment]
Issue is solved in ZHC 23.36.0
Would be nice to have it here 😃

**Comment by asgothian** [comment]
Install the ZHC_latest branch to get the ZHC version.

Note - this has not been tested by me, so there may be side effects.

A.

**Comment by Shakira10** [comment]
> Install the ZHC_latest branch to get the ZHC version.
> 
> Note - this has not been tested by me, so there may be side effects.
> 
> A.

Good evening,
update made, problem was not solved.
Zigbee also crashes...

**Comment by asgothian** [comment]
> > Install the ZHC_latest branch to get the ZHC version.
> > Note - this has not been tested by me, so there may be side effects.
> > A.
> 
> Good evening, update made, problem was not solved. Zigbee also crashes...

details ?

**Comment by asgothian** [comment]
Please verify the ZHC version installed and the device firmware version..With the correct ZHC version installed (newer than 23.36.0) there’s no code in the adapter which affects this. The entire code is within ZHC and the device firmware.

**Comment by asgothian** [comment]
There has been a misunderstanding between @arteck and me. Please install the ZHC_latest branch to get the correct ZHC version

**Comment by asgothian** [comment]
please test with the ZHC_latest branch, installable from this link:

https://github.com/ioBroker/ioBroker.zigbee/tarball/ZHC_latest

**Comment by TbsJah** [comment]
Maybe I have done something wrong
I am not able to download the version of ZHC
. I received an error message after the installation via adapater upload

<img width="1502" height="406" alt="Image" src="https://github.com/user-attachments/assets/73cea2cf-8be0-4c4d-a8f4-e0977647cb2d" />

**Comment by asgothian** [comment]
Please run the installation with additional information selected in the dialogue and then paste the complete installation. Log from that dialogue. keep in mind. You may have to check the box at do not close at exit to access the log.

**Comment by TbsJah** [comment]
forgot to stop the instance ^^ 
now it works

many thanks!!

**Comment by asgothian** [comment]
fixed in current github version
